version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
  
  backend:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./backend
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
    container_name: mysql-app
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aws_project
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
    
